export const productLocators = {
    productTitle: ".title",
    productItem: ".inventory_item",
    productName: ".inventory_item_name",
    productDescription: ".inventory_item_desc",
    productPrice: ".inventory_item_price",
    addToCartButton: ".btn_inventory",
    shoppingCartBadge: ".shopping_cart_badge",
    shoppingCartLink: ".shopping_cart_link",
    menu: "#react-burger-menu-btn",
    logoutLink: "#logout_sidebar_link",
    aboutLink: "#about_sidebar_link",
    resetAppStateLink: "#reset_sidebar_link",
    closeMenuButton: "#react-burger-cross-btn",
    requestdemoLink: 'a[href="/request-demo"]',
    loginButton: '#login-button',
    filterDropdown: ".product_sort_container",
    filterAtoZOption: 'option[value="az"]',
    filterZtoAOption: 'option[value="za"]',
    filterLowToHighOption: 'option[value="lohi"]',
    filterHighToLowOption: 'option[value="hilo"]',
    cartlink: ".shopping_cart_link",
}